#!/bin/bash

sudo apt-get update || exit 1
sudo apt-get install python2.6 \
    python2.6-dev \
    python-virtualenv \
    python-distribute  \
    build-essential \
    git-core \
    subversion \
    postgresql-8.4-postgis \
    python-gdal \
    python-lxml \
    libproj0 \
    libproj-dev || exit 1

sudo ldconfig || exit 1
echo Rebooting
sudo reboot
