#!/bin/bash

sudo apt-get update || exit 1

# cleanup dev dependencies in case we've run the other scenario before...
echo Cleanup...
sudo apt-get remove libgdal1-1.6.0 \
    libgdal1-dev \
    libxml2 libxml2-dev \
    libxslt1 libxslt1.1-dev

# echo More cleanup...
# sudo apt-get autoremove

sudo ldconfig

sudo apt-get install python2.6 \
    python2.6-dev \
    python-virtualenv \
    python-distribute  \
    build-essential \
    git-core \
    subversion \
    postgresql-8.4-postgis \
    python-gdal \
    python-lxml \
    libproj0 \
    libproj-dev \
    python-psycopg2 || exit 1

sudo ldconfig || exit 1
#echo Rebooting
#sudo reboot
