#!/bin/bash
# Start/stop the updaterdaemon. This is copied largely from the cron init script.
#
### BEGIN INIT INFO
# Provides:          updaterdaemon
# Required-Start:    $syslog $time
# Required-Stop:     $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      S 0 1 6
# Short-Description: Regular background program processing daemon
# Description:       updaterdaemon is a Python cron replacement.

### END INIT INFO

#LSBNAMES='-l'  # Uncomment for LSB name support in /etc/cron.d/

# Reliably (hah!) and portably (?) find the directory containing this script.
# Based roughly on stuff from:
# http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-in
HERE=`(cd $(dirname $(readlink -f "${0}")) 2>/dev/null; echo "$PWD"/)`

# What if we're on a non-Linux *nix?
. /lib/lsb/init-functions

# Find a local python if there is one (eg. in a virtualenv).
PYTHON=`which python`
cd $HERE
while [ true ]; do
    if [ $PWD == '/' ]; then
	break
    elif [ -x ./bin/python ]; then
	PYTHON=$PWD/bin/python
	break
    elif [ -x python ]; then
	PYTHON=$PWD/python
	break
    else
	cd ..
    fi
done

RUNNER="$PYTHON $HERE/runner.py"
SUUSER="pw"

case "$1" in
start)	log_begin_msg "Starting updaterdaemon..."
        sudo -u $SUUSER $RUNNER start
        log_end_msg $?
	;;
stop)	log_begin_msg "Stopping updaterdaemon..."
        sudo -u $SUUSER $RUNNER stop
        log_end_msg $?
        ;;
restart) log_begin_msg "Restarting updaterdaemon..."
        sudo -u $SUUSER $RUNNER restart
        log_end_msg $?
        ;;
*)	log_success_msg "Usage: /etc/init.d/updaterdaemon start|stop|restart"
        exit 1 
        ;;
esac
exit 0
